import { useState, useMemo } from "react";

const fmt = n => new Intl.NumberFormat("en-US").format(n);
const fp = n => n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(0)}K`:`$${fmt(n)}`;
const pmt = (p,r,y=30)=>{const mr=r/100/12,n=y*12;return mr===0?p/n:p*(mr*Math.pow(1+mr,n))/(Math.pow(1+mr,n)-1);};
const T={bg:"#f8fafc",card:"#fff",bdr:"#e8ecf1",shd:"0 1px 3px rgba(0,0,0,0.04),0 1px 2px rgba(0,0,0,0.02)",tx:"#1e293b",sc:"#64748b",mt:"#94a3b8",lb:"#0891b2",br:"#10b981",brd:"#059669",ch:"#6366f1",pos:"#10b981",neg:"#ef4444",wrn:"#f59e0b",bl:"#3b82f6",pu:"#8b5cf6"};
const R={u:"Feb 10, 2026",c30:{r:6.11,l:"30-Yr Fixed"},c15:{r:5.50,l:"15-Yr Fixed"},fha:{r:5.75,l:"FHA 30-Yr",n:"3.5% min down"},va:{r:5.375,l:"VA 30-Yr",n:"0% down"},jb:{r:6.25,l:"Jumbo"},arm:{r:5.63,l:"5/1 ARM"},trend:[{w:"Jan 2",r:6.91},{w:"Jan 9",r:6.93},{w:"Jan 16",r:6.89},{w:"Jan 23",r:6.87},{w:"Jan 30",r:6.63},{w:"Feb 6",r:6.11}]};
const M={med:1865000,chg:-5.6,dom:45,dp:40,s30:46,sp:33,ppsf:976,pc:5.1,comp:66,off:5,hd:12,ls:98,act:146,rent:2450,mig:{stay:74,from:["Los Angeles","Raleigh","San Francisco"],to:["Portland","Nashville","Phoenix"]},trend:[{m:"Mar '25",p:1720000},{m:"May",p:1810000},{m:"Jul",p:1920000},{m:"Sep",p:1960000},{m:"Nov",p:1890000},{m:"Jan '26",p:1865000}]};
const H=[{id:"leucadia",nm:"Leucadia",med:2990000,chg:19.6,dom:46,sc:52,hot:16,ppsf:1285,act:28,s30:8,vb:"Surf-town soul, Coast Hwy culture",cl:"#6366f1",sch:[{n:"Paul Ecke Central",r:8}]},{id:"old-encinitas",nm:"Old Encinitas",med:2100000,chg:5.7,dom:42,sc:66,hot:13,ppsf:1120,act:31,s30:11,vb:"Downtown walkability, village charm",cl:"#0ea5e9",sch:[{n:"Flora Vista",r:8},{n:"San Dieguito Academy",r:9}]},{id:"new-encinitas",nm:"New Encinitas",med:1452500,chg:9.2,dom:17,sc:72,hot:10,ppsf:780,act:38,s30:14,vb:"Family-friendly, great schools",cl:"#10b981",sch:[{n:"Park Dale Lane",r:9}]},{id:"olivenhain",nm:"Olivenhain",med:1570000,chg:19.3,dom:11,sc:86,hot:6,ppsf:690,act:22,s30:8,vb:"Equestrian estates, rural luxury",cl:"#f59e0b",sch:[{n:"Olivenhain Pioneer",r:9}]},{id:"cardiff",nm:"Cardiff-by-the-Sea",med:2000000,chg:-8.5,dom:39,sc:55,hot:8,ppsf:1050,act:27,s30:5,vb:"Restaurant Row, beach village life",cl:"#ef4444",sch:[{n:"Cardiff Elementary",r:8}]}];
const SL=[{a:"412 Neptune Ave",h:"Leucadia",p:2150000,bd:3,ba:2,sf:1820,dm:8,st:"Active",pf:1181},{a:"225 W D St",h:"Old Encinitas",p:1650000,bd:2,ba:2,sf:1450,dm:5,st:"Pending",pf:1138},{a:"1745 Gascony Rd",h:"New Encinitas",p:1520000,bd:4,ba:2.5,sf:2100,dm:12,st:"Active",pf:724},{a:"3455 Lone Hill Ln",h:"Olivenhain",p:3250000,bd:5,ba:4,sf:4200,dm:42,st:"Price Cut",pf:774},{a:"2102 Oxford Ave",h:"Cardiff",p:2450000,bd:3,ba:2,sf:1680,dm:3,st:"Just Listed",pf:1458},{a:"965 Santa Fe Dr",h:"Old Encinitas",p:1780000,bd:3,ba:2,sf:1720,dm:1,st:"Just Listed",pf:1035}];
const PT={adu:{l:"ADU",i:"🏠",c:"#8b5cf6",s:"Investment — likely holding"},newcon:{l:"New Construction",i:"🏗️",c:"#3b82f6",s:"New inventory incoming"},remodel:{l:"Major Remodel",i:"🔨",c:"#f59e0b",s:"Owner improving, likely staying"},solar:{l:"Solar",i:"☀️",c:"#10b981",s:"Long-term hold"},demo:{l:"Demolition",i:"🏚️",c:"#ef4444",s:"Possible tear-down or estate"},roof:{l:"Roof",i:"🏡",c:"#64748b",s:"Maintenance or pre-sale prep"},electric:{l:"Electrical",i:"⚡",c:"#eab308",s:"EV charger / panel upgrade"},pool:{l:"Pool",i:"🏊",c:"#0ea5e9",s:"Lifestyle investment"}};
const PM=[{d:"Feb 7",a:"412 Neptune Ave",h:"leucadia",t:"adu",v:185000,ds:"Detached ADU 650sf",s:"Approved"},{d:"Feb 5",a:"1033 Hermes Ave",h:"leucadia",t:"solar",v:32000,ds:"10.2kW rooftop solar",s:"Approved"},{d:"Feb 4",a:"225 W D St",h:"old-encinitas",t:"remodel",v:275000,ds:"Kitchen/bath + ADU conversion",s:"Under Review"},{d:"Feb 3",a:"3455 Lone Hill Ln",h:"olivenhain",t:"pool",v:95000,ds:"In-ground pool + outdoor kitchen",s:"Approved"},{d:"Jan 31",a:"2102 Oxford Ave",h:"cardiff",t:"roof",v:28000,ds:"Complete roof replacement",s:"Approved"},{d:"Jan 30",a:"560 Requeza St",h:"old-encinitas",t:"adu",v:210000,ds:"Attached ADU 800sf",s:"Approved"},{d:"Jan 25",a:"3020 Via de Caballo",h:"olivenhain",t:"newcon",v:1850000,ds:"New SFR 4,200sf",s:"Under Review"},{d:"Jan 22",a:"2478 Cambridge Ave",h:"cardiff",t:"demo",v:0,ds:"Full demolition",s:"Approved"}];
const DP=[{nm:"Encinitas Blvd Specific Plan",st:"In Progress",sc:"380 units + 45K sf retail",tl:"2024-2028",h:"new-encinitas",d:"Major corridor redevelopment. Expected long-term value boost."},{nm:"Leucadia Streetscape",st:"Phase 2",sc:"$25M+ public improvement",tl:"2023-2027",h:"leucadia",d:"Protected bike lanes, roundabouts. Expected 8-15% value lift within 0.25mi."},{nm:"Pacific View School Site",st:"Planning",sc:"Up to 120 townhomes",tl:"2025-2029",h:"old-encinitas",d:"Former school site redevelopment. Adds inventory in ultra-tight market."},{nm:"Cardiff Town Center",st:"Approved",sc:"60 units + retail",tl:"2025-2028",h:"cardiff",d:"Mixed-use on San Elijo Ave. Walkability boost."}];
const MICROS={"old-encinitas":[{nm:"Downtown Village",pf:1250,tr:7.4,vb:"Walk to Moonlight Beach"},{nm:"West of 101",pf:1380,tr:5.2,vb:"Ocean views, coastal access"},{nm:"East Village",pf:920,tr:9.1,vb:"Quieter, family-oriented"}],leucadia:[{nm:"Beacons/Grandview",pf:1420,tr:8.2,vb:"Oceanfront, surf breaks"},{nm:"Coast Hwy Corridor",pf:1180,tr:6.1,vb:"Walkable shops & restaurants"},{nm:"East of 101",pf:985,tr:4.3,vb:"Quieter, larger lots"}],"new-encinitas":[{nm:"Saxony/Park Dale",pf:810,tr:10.3,vb:"Top schools"},{nm:"Village Park",pf:760,tr:8.8,vb:"Large lots"},{nm:"El Camino Real",pf:720,tr:11.2,vb:"Newer builds"}],olivenhain:[{nm:"Rancho Santa Fe Rd",pf:750,tr:18.1,vb:"Horse properties"},{nm:"Lone Hill",pf:680,tr:15.4,vb:"Custom estates"},{nm:"Elfin Forest Adj",pf:620,tr:22.3,vb:"Trail access"}],cardiff:[{nm:"Restaurant Row",pf:1180,tr:-6.2,vb:"Walk to dining"},{nm:"Composer District",pf:1050,tr:-4.8,vb:"Residential quiet"},{nm:"San Elijo Hills",pf:880,tr:-2.1,vb:"Views, newer"}]};
const BP={leucadia:{pr:"Remote tech, 30-45",bg:"$1.8M-$3.5M",ft:["Surf proximity","ADU potential","Character"],or:"70% LA/Bay Area",fi:"65% conv, 15% jumbo, 12% cash"},
"old-encinitas":{pr:"Young pros & downsizers",bg:"$1.5M-$2.5M",ft:["Walkability","Outdoor space","Historic charm"],or:"55% local, 30% LA",fi:"60% conv, 20% jumbo, 15% cash"},
"new-encinitas":{pr:"Families w/ school-age kids",bg:"$1.2M-$1.8M",ft:["4+ bedrooms","Top schools","Cul-de-sacs"],or:"40% local, 35% LA/OC",fi:"55% conv, 20% FHA, 15% VA"},
olivenhain:{pr:"Executives, equestrian",bg:"$1.5M-$3.5M",ft:["1+ acre","Horse facilities","Privacy"],or:"45% local, 30% LA",fi:"50% jumbo, 30% cash"},
cardiff:{pr:"Retirees & lifestyle",bg:"$1.8M-$3M",ft:["Single-story","Restaurant Row","Low maintenance"],or:"50% local downsizer",fi:"45% cash, 35% conv"}};

const Logo=({sz=36})=><svg width={sz} height={sz} viewBox="0 0 36 36" fill="none"><rect width="36" height="36" rx="10" fill="#10b981"/><path d="M18 8L9 15.5V27H15V21H21V27H27V15.5L18 8Z" fill="white" opacity="0.3"/><path d="M10 24L14.5 19L18 21.5L22 15L26 11" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M23 11H26V14" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/><circle cx="14.5" cy="19" r="1.5" fill="white"/><circle cx="18" cy="21.5" r="1.5" fill="white"/><circle cx="22" cy="15" r="1.5" fill="white"/></svg>;
const LogoSm=({sz=20})=><svg width={sz} height={sz} viewBox="0 0 36 36" fill="none"><rect width="36" height="36" rx="10" fill="#10b981"/><path d="M10 24L14.5 19L18 21.5L22 15L26 11" stroke="white" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><path d="M23 11H26V14" stroke="white" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const Lb=({children,s})=><div style={{fontSize:11,fontWeight:700,color:T.lb,textTransform:"uppercase",letterSpacing:"1.2px",...s}}>{children}</div>;
const Cd=({children,s,...r})=><div style={{background:T.card,border:`1px solid ${T.bdr}`,borderRadius:16,boxShadow:T.shd,...s}} {...r}>{children}</div>;
const Bg=({st})=>{const m={Active:[T.pos,"#ecfdf5","●"],Pending:[T.wrn,"#fffbeb","◆"],"Price Cut":[T.neg,"#fef2f2","↓"],"Just Listed":[T.bl,"#eff6ff","★"]};const[c,bg,i]=m[st]||[T.mt,"#f1f5f9","·"];return<span style={{fontSize:12,fontWeight:700,padding:"4px 12px",borderRadius:20,background:bg,color:c,whiteSpace:"nowrap"}}>{i} {st}</span>;};
const Ring=({v,sz=100})=>{const r=(sz-10)/2,c=2*Math.PI*r,p=v/100,cl=v>=70?T.neg:v>=50?T.wrn:T.pos;return<svg width={sz} height={sz}><circle cx={sz/2} cy={sz/2} r={r} fill="none" stroke="#f1f5f9" strokeWidth="6"/><circle cx={sz/2} cy={sz/2} r={r} fill="none" stroke={cl} strokeWidth="6" strokeDasharray={`${c*p} ${c*(1-p)}`} strokeDashoffset={c*0.25} strokeLinecap="round"/><text x={sz/2} y={sz/2+1} textAnchor="middle" dominantBaseline="middle" style={{fontSize:sz*0.32,fontWeight:900,fill:T.tx}}>{v}</text></svg>;};
const Cht=({data,w=320,h=100})=>{if(!data||data.length<2)return null;const ps=data.map(d=>d.p),mn=Math.min(...ps)*0.97,mx=Math.max(...ps)*1.01;const pts=data.map((d,i)=>[(i/(data.length-1))*w,(h-8)-((d.p-mn)/(mx-mn))*(h-24)]);const pD=pts.map((p,i)=>i===0?`M${p[0]},${p[1]}`:`L${p[0]},${p[1]}`).join(" ");const aD=pD+` L${pts[pts.length-1][0]},${h-8} L${pts[0][0]},${h-8} Z`;return<svg width={w} height={h+18} style={{display:"block",width:"100%"}} viewBox={`0 0 ${w} ${h+18}`} preserveAspectRatio="none"><defs><linearGradient id="cg" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={T.ch} stopOpacity="0.15"/><stop offset="100%" stopColor={T.ch} stopOpacity="0"/></linearGradient></defs><path d={aD} fill="url(#cg)"/><path d={pD} fill="none" stroke={T.ch} strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>{data.map((d,i)=><text key={i} x={pts[i][0]} y={h+14} textAnchor="middle" style={{fontSize:9,fill:T.mt}}>{d.m}</text>)}</svg>;};

/* ── DASHBOARD ── */
function Dash(){const sc=Math.round((M.s30/M.sp-1)*100);return<><div style={{marginBottom:32}}><div style={{display:"inline-flex",alignItems:"center",gap:8,padding:"6px 16px",borderRadius:20,background:"#ecfdf5",marginBottom:16}}><div style={{width:6,height:6,borderRadius:3,background:T.br}}/><span style={{fontSize:11,fontWeight:700,color:T.brd,textTransform:"uppercase",letterSpacing:"1px"}}>Live Market Intelligence · February 2026</span></div><h1 style={{fontSize:48,fontWeight:900,color:T.tx,letterSpacing:"-2.5px",margin:0,lineHeight:1}}>Encinitas</h1><h1 style={{fontSize:48,fontWeight:900,color:T.br,letterSpacing:"-2.5px",margin:0,lineHeight:1.1}}>Real Estate</h1><p style={{fontSize:16,color:T.sc,marginTop:12,lineHeight:1.5,maxWidth:500}}>Neighborhood-level market data powered by MLS & Redfin.<br/>Updated weekly for buyers, sellers, and investors.</p></div>
<div style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr",gap:16,marginBottom:16}}><Cd s={{padding:"24px 28px"}}><Lb>Median Sale Price</Lb><div style={{fontSize:42,fontWeight:900,color:T.tx,letterSpacing:"-2px",marginTop:6}}>{fp(M.med)}</div><div style={{display:"flex",alignItems:"center",gap:8,marginTop:6}}><span style={{fontSize:13,fontWeight:700,padding:"2px 10px",borderRadius:8,background:"#fef2f2",color:T.neg}}>↓ {Math.abs(M.chg)}%</span><span style={{fontSize:13,color:T.mt}}>vs last year</span></div><div style={{marginTop:16}}><Cht data={M.trend}/></div></Cd><Cd s={{padding:"28px 20px",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><Ring v={M.comp}/><Lb s={{marginTop:12,textAlign:"center"}}>Compete Score</Lb></Cd><Cd s={{padding:"24px 28px"}}><Lb>Homes Sold · 30d</Lb><div style={{fontSize:42,fontWeight:900,color:T.tx,letterSpacing:"-2px",marginTop:6}}>{M.s30}</div><span style={{fontSize:13,fontWeight:700,color:T.pos}}>↑ {sc}% YoY</span></Cd></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:32}}><Cd s={{padding:"24px 28px"}}><Lb>Days on Market</Lb><div style={{fontSize:42,fontWeight:900,color:T.tx,letterSpacing:"-2px",marginTop:6}}>{M.dom}<span style={{fontSize:16,color:T.mt,fontWeight:400}}> avg</span></div></Cd><Cd s={{padding:"24px 28px"}}><Lb>Price / Sq Ft</Lb><div style={{fontSize:42,fontWeight:900,color:T.tx,letterSpacing:"-2px",marginTop:6}}>${M.ppsf}</div><span style={{fontSize:13,fontWeight:700,color:T.pos}}>↑ {M.pc}% YoY</span></Cd></div>
<h2 style={{fontSize:28,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:"0 0 20px"}}>Neighborhoods</h2>
<div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:12,marginBottom:32}}>{H.map(n=>{const cc=n.sc>=70?T.neg:n.sc>=50?T.wrn:T.pos;return<Cd key={n.id} s={{padding:0,overflow:"hidden"}}><div style={{height:4,background:n.cl}}/><div style={{padding:"18px 18px 16px"}}><div style={{fontSize:15,fontWeight:800,color:T.tx}}>{n.nm}</div><div style={{fontSize:11,color:T.mt,marginTop:2,minHeight:30}}>{n.vb}</div><div style={{fontSize:26,fontWeight:900,color:T.tx,letterSpacing:"-1px",marginTop:10}}>{fp(n.med)}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:6}}><span style={{fontSize:12,fontWeight:700,color:n.chg>0?T.pos:T.neg}}>{n.chg>0?"↑":"↓"} {Math.abs(n.chg)}%</span><span style={{fontSize:12,color:T.mt}}>{n.dom}d</span></div><div style={{display:"flex",justifyContent:"space-between",marginTop:10}}><span style={{fontSize:11,color:T.sc}}>Compete</span><span style={{fontSize:13,fontWeight:800,color:cc}}>{n.sc}</span></div><div style={{height:4,borderRadius:2,background:"#f1f5f9",marginTop:4,overflow:"hidden"}}><div style={{height:"100%",width:`${n.sc}%`,borderRadius:2,background:cc}}/></div></div></Cd>})}</div>
<Cd s={{padding:0,overflow:"hidden"}}><div style={{padding:"18px 24px",display:"flex",justifyContent:"space-between",borderBottom:`1px solid ${T.bdr}`}}><Lb>Recent Listings</Lb><span style={{fontSize:12,fontWeight:700,color:T.br,padding:"4px 12px",borderRadius:20,background:"#ecfdf5"}}>{M.act} active</span></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr style={{borderBottom:`1px solid ${T.bdr}`}}>{["Address","Area","Bd/Ba","Price","DOM","Status"].map(h=><th key={h} style={{padding:"12px 16px",textAlign:"left",fontSize:10,fontWeight:700,color:T.lb,textTransform:"uppercase",letterSpacing:"1px"}}>{h}</th>)}</tr></thead><tbody>{SL.map((s,i)=><tr key={i} style={{borderBottom:`1px solid ${T.bdr}`}}><td style={{padding:"14px 16px",fontWeight:700,color:T.tx}}>{s.a}</td><td style={{padding:"14px 16px",color:T.sc}}>{s.h}</td><td style={{padding:"14px 16px",color:T.sc}}>{s.bd}/{s.ba}</td><td style={{padding:"14px 16px",fontWeight:800,color:T.tx}}>{fp(s.p)}</td><td style={{padding:"14px 16px",color:T.sc}}>{s.dm}</td><td style={{padding:"14px 16px"}}><Bg st={s.st}/></td></tr>)}</tbody></table></Cd></>;}

/* ── PERMITS ── */
function Permits(){const[fH,sfH]=useState("all"),[fT,sfT]=useState("all");const fl=useMemo(()=>{let l=PM;if(fH!=="all")l=l.filter(p=>p.h===fH);if(fT!=="all")l=l.filter(p=>p.t===fT);return l;},[fH,fT]);return<><h1 style={{fontSize:28,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:"0 0 6px"}}>Permits & Development</h1><p style={{fontSize:14,color:T.mt,marginBottom:24}}>Building permits, ADU filings, and city development projects</p>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}>{[["Permits (90d)","76",T.ch],["ADU Filings","16",T.pu],["New Construction","6",T.bl],["Permit Value","$8.4M",T.br]].map(([l,v,c])=><Cd key={l} s={{padding:"20px 24px"}}><Lb>{l}</Lb><div style={{fontSize:36,fontWeight:900,color:c,letterSpacing:"-1.5px",marginTop:6}}>{v}</div></Cd>)}</div>
<Cd s={{padding:"24px 28px",marginBottom:24,background:"#f0fdf4",border:"1px solid #bbf7d0"}}><Lb s={{color:T.brd,marginBottom:12}}>🔍 What Permits Signal</Lb><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{Object.entries(PT).map(([k,p])=><div key={k} style={{padding:"10px 14px",borderRadius:10,background:"rgba(255,255,255,0.8)"}}><div style={{fontSize:14,marginBottom:4}}>{p.i} <span style={{fontWeight:700,color:p.c}}>{p.l}</span></div><div style={{fontSize:11,color:T.sc,lineHeight:1.4}}>{p.s}</div></div>)}</div></Cd>
<Cd s={{padding:0,overflow:"hidden",marginBottom:24}}><div style={{padding:"18px 24px",borderBottom:`1px solid ${T.bdr}`,display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:12}}><Lb>Recent Permits</Lb><div style={{display:"flex",gap:8}}><select value={fH} onChange={e=>sfH(e.target.value)} style={{padding:"6px 12px",borderRadius:8,fontSize:12,border:`1px solid ${T.bdr}`,background:T.card,color:T.tx,fontWeight:600}}><option value="all">All Areas</option>{H.map(n=><option key={n.id} value={n.id}>{n.nm}</option>)}</select><select value={fT} onChange={e=>sfT(e.target.value)} style={{padding:"6px 12px",borderRadius:8,fontSize:12,border:`1px solid ${T.bdr}`,background:T.card,color:T.tx,fontWeight:600}}><option value="all">All Types</option>{Object.entries(PT).map(([k,v])=><option key={k} value={k}>{v.i} {v.l}</option>)}</select></div></div>
<table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr style={{borderBottom:`1px solid ${T.bdr}`}}>{["Date","Address","Type","Value","Description","Status"].map(h=><th key={h} style={{padding:"10px 14px",textAlign:"left",fontSize:10,fontWeight:700,color:T.lb,textTransform:"uppercase",letterSpacing:"1px"}}>{h}</th>)}</tr></thead><tbody>{fl.map((p,i)=>{const pt=PT[p.t];return<tr key={i} style={{borderBottom:`1px solid ${T.bdr}`}}><td style={{padding:"12px 14px",color:T.sc,fontSize:13}}>{p.d}</td><td style={{padding:"12px 14px",fontWeight:700,color:T.tx}}>{p.a}</td><td style={{padding:"12px 14px"}}><span style={{fontSize:12,fontWeight:700,padding:"3px 10px",borderRadius:6,background:`${pt.c}12`,color:pt.c}}>{pt.i} {pt.l}</span></td><td style={{padding:"12px 14px",fontWeight:700,color:T.tx}}>{p.v>0?`$${fmt(p.v)}`:"—"}</td><td style={{padding:"12px 14px",color:T.sc,fontSize:13}}>{p.ds}</td><td style={{padding:"12px 14px"}}><span style={{fontSize:11,fontWeight:700,padding:"3px 10px",borderRadius:6,background:p.s==="Approved"?"#ecfdf5":"#fefce8",color:p.s==="Approved"?T.pos:T.wrn}}>{p.s}</span></td></tr>})}</tbody></table></Cd>
<h2 style={{fontSize:22,fontWeight:900,color:T.tx,margin:"0 0 16px"}}>City Development Projects</h2>
{DP.map((p,i)=>{const hd=H.find(n=>n.id===p.h),sc=p.st==="Approved"?T.pos:p.st==="In Progress"?T.bl:p.st==="Phase 2"?T.wrn:T.pu;return<Cd key={i} s={{padding:0,overflow:"hidden",marginBottom:12}}><div style={{display:"flex",borderLeft:`4px solid ${hd?.cl||T.mt}`}}><div style={{flex:1,padding:"18px 24px"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><span style={{fontSize:15,fontWeight:800,color:T.tx}}>{p.nm}</span><span style={{fontSize:10,fontWeight:700,padding:"3px 10px",borderRadius:6,background:`${sc}15`,color:sc}}>{p.st}</span></div><div style={{fontSize:12,color:T.sc,marginBottom:6}}><strong>{p.sc}</strong> · {p.tl} · {hd?.nm}</div><div style={{fontSize:13,color:T.sc,lineHeight:1.5}}>{p.d}</div></div></div></Cd>})}</>;}

/* ── INTEL REPORT ── */
function Intel(){const[hood,sH]=useState("old-encinitas"),[addr,sA]=useState(""),[bd,sBd]=useState(3),[ba,sBa]=useState(2),[sf,sSf]=useState(1800),[gen,sG]=useState(false);const h=H.find(n=>n.id===hood)||H[0],mc=MICROS[hood]||[],bp=BP[hood]||{},ev=Math.round(sf*h.ppsf),comps=SL.slice(0,4);
const inp={width:"100%",padding:"12px 16px",borderRadius:10,border:`1px solid ${T.bdr}`,fontSize:14,fontFamily:"inherit",outline:"none",boxSizing:"border-box",color:T.tx};
return<><h1 style={{fontSize:28,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:"0 0 6px"}}>Property Intelligence Report</h1><p style={{fontSize:14,color:T.mt,marginBottom:24}}>AI-powered analysis for listing appointments</p>
{!gen?<Cd s={{padding:32,maxWidth:600}}><Lb s={{marginBottom:16}}>Generate Report</Lb><div style={{marginBottom:12}}><div style={{fontSize:12,fontWeight:700,color:T.sc,marginBottom:4}}>Property Address</div><input value={addr} onChange={e=>sA(e.target.value)} placeholder="e.g. 560 Requeza St" style={inp}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:12,marginBottom:12}}><div><div style={{fontSize:12,fontWeight:700,color:T.sc,marginBottom:4}}>Neighborhood</div><select value={hood} onChange={e=>sH(e.target.value)} style={{...inp,padding:"10px 12px",fontSize:13}}>{H.map(n=><option key={n.id} value={n.id}>{n.nm}</option>)}</select></div><div><div style={{fontSize:12,fontWeight:700,color:T.sc,marginBottom:4}}>Beds</div><input type="number" value={bd} onChange={e=>sBd(+e.target.value)} style={inp}/></div><div><div style={{fontSize:12,fontWeight:700,color:T.sc,marginBottom:4}}>Baths</div><input type="number" value={ba} onChange={e=>sBa(+e.target.value)} style={inp}/></div><div><div style={{fontSize:12,fontWeight:700,color:T.sc,marginBottom:4}}>Sq Ft</div><input type="number" value={sf} onChange={e=>sSf(+e.target.value)} style={inp}/></div></div><button onClick={()=>addr&&sG(true)} style={{marginTop:8,padding:"14px",borderRadius:12,border:"none",fontSize:15,fontWeight:700,background:T.br,color:"white",cursor:"pointer",width:"100%"}}>Generate Intelligence Report</button></Cd>:<>
<Cd s={{padding:"24px 28px",marginBottom:16,borderLeft:`4px solid ${h.cl}`}}><div style={{display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:16}}><div><Lb s={{marginBottom:6}}>Property Intelligence Report</Lb><h2 style={{fontSize:24,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:0}}>{addr}</h2><div style={{fontSize:14,color:T.sc,marginTop:4}}>{h.nm} · {bd}bd/{ba}ba · {fmt(sf)}sf</div></div><div style={{textAlign:"right"}}><div style={{fontSize:11,color:T.lb,fontWeight:700}}>ESTIMATED VALUE</div><div style={{fontSize:36,fontWeight:900,color:T.br,letterSpacing:"-2px"}}>{fp(ev)}</div><div style={{fontSize:12,color:T.sc}}>${h.ppsf}/sqft</div></div></div><button onClick={()=>sG(false)} style={{marginTop:12,padding:"8px 16px",borderRadius:8,border:`1px solid ${T.bdr}`,background:T.card,color:T.sc,fontSize:12,fontWeight:600,cursor:"pointer"}}>← New Report</button></Cd>

{/* Comps */}
<Cd s={{padding:"24px 28px",marginBottom:16}}><Lb s={{marginBottom:16}}>📊 Comparable Sales</Lb><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{borderBottom:`1px solid ${T.bdr}`}}>{["Property","Bd/Ba","Sq Ft","Price","$/Sqft","DOM","Status"].map(x=><th key={x} style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:T.lb,textTransform:"uppercase",letterSpacing:"0.5px"}}>{x}</th>)}</tr></thead><tbody><tr style={{background:"#ecfdf5",borderBottom:`1px solid ${T.bdr}`}}><td style={{padding:"12px",fontWeight:800,color:T.br}}>📍 Subject</td><td style={{padding:"12px"}}>{bd}/{ba}</td><td style={{padding:"12px"}}>{fmt(sf)}</td><td style={{padding:"12px",fontWeight:800}}>{fp(ev)}</td><td style={{padding:"12px"}}>${h.ppsf}</td><td style={{padding:"12px"}}>—</td><td style={{padding:"12px"}}>—</td></tr>{comps.map((c,i)=><tr key={i} style={{borderBottom:`1px solid ${T.bdr}`}}><td style={{padding:"12px",fontWeight:700,color:T.tx}}>{c.a}</td><td style={{padding:"12px",color:T.sc}}>{c.bd}/{c.ba}</td><td style={{padding:"12px",color:T.sc}}>{fmt(c.sf)}</td><td style={{padding:"12px",fontWeight:700}}>{fp(c.p)}</td><td style={{padding:"12px",fontWeight:700}}>${c.pf}</td><td style={{padding:"12px",color:T.sc}}>{c.dm}d</td><td style={{padding:"12px"}}><Bg st={c.st}/></td></tr>)}</tbody></table></Cd>

{/* Micro-neighborhoods */}
<Cd s={{padding:"24px 28px",marginBottom:16}}><Lb s={{marginBottom:16}}>🗺️ Micro-Neighborhoods — {h.nm}</Lb><div style={{display:"grid",gridTemplateColumns:`repeat(${mc.length},1fr)`,gap:12}}>{mc.map((m,i)=><div key={i} style={{padding:16,borderRadius:12,border:`1px solid ${T.bdr}`,background:i===0?`${h.cl}08`:T.card}}><div style={{fontSize:14,fontWeight:800,color:T.tx}}>{m.nm}</div><div style={{fontSize:11,color:T.sc,marginBottom:10}}>{m.vb}</div><div style={{fontSize:22,fontWeight:900,color:T.tx}}>${m.pf}<span style={{fontSize:12,color:T.mt}}>/sqft</span></div><span style={{fontSize:12,fontWeight:700,color:m.tr>0?T.pos:T.neg}}>{m.tr>0?"↑":"↓"} {Math.abs(m.tr)}%</span><div style={{marginTop:8,fontSize:12,fontWeight:700,color:T.tx}}>At {fmt(sf)}sf: {fp(sf*m.pf)}</div></div>)}</div></Cd>

{/* Buyer Profile */}
<Cd s={{padding:"24px 28px",marginBottom:16}}><Lb s={{marginBottom:16}}>👤 Buyer Profile — {h.nm}</Lb><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}><div>{[["Primary Buyer",bp.pr],["Budget",bp.bg],["Origin",bp.or],["Financing",bp.fi]].map(([l,v])=><div key={l} style={{marginBottom:14}}><div style={{fontSize:11,fontWeight:700,color:T.lb,textTransform:"uppercase",letterSpacing:"0.5px"}}>{l}</div><div style={{fontSize:14,color:T.tx,marginTop:2,fontWeight:600}}>{v}</div></div>)}</div><div><div style={{fontSize:11,fontWeight:700,color:T.lb,textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:8}}>Top Features</div>{(bp.ft||[]).map((f,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 0",borderBottom:"1px solid #f1f5f9"}}><span style={{color:T.br,fontWeight:700}}>#{i+1}</span><span style={{fontSize:14,color:T.tx}}>{f}</span></div>)}</div></div></Cd>

{/* Pricing Scenarios */}
<Cd s={{padding:"24px 28px",marginBottom:16}}><Lb s={{marginBottom:16}}>💰 Pricing Strategy</Lb><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10}}>{[{l:"Aggressive",pc:1.05,dm:"7-14d",c:T.neg},{l:"Market Value",pc:1.00,dm:"21-35d",c:T.br},{l:"Aspirational",pc:0.95,dm:"45-60d",c:T.wrn},{l:"Premium",pc:0.92,dm:"60-90d+",c:T.mt}].map(s=>{const sp=Math.round(ev*s.pc),net=Math.round(sp*0.95);return<div key={s.l} style={{padding:16,borderRadius:12,border:`2px solid ${s.c}22`,background:`${s.c}06`}}><div style={{fontSize:12,fontWeight:800,color:s.c}}>{s.l}</div><div style={{fontSize:20,fontWeight:900,color:T.tx,marginTop:6}}>{fp(sp)}</div><div style={{fontSize:11,color:T.sc,marginTop:4}}>DOM: {s.dm}</div><div style={{marginTop:8,paddingTop:8,borderTop:`1px solid ${T.bdr}`}}><div style={{fontSize:10,color:T.mt}}>Seller net</div><div style={{fontSize:16,fontWeight:800,color:T.tx}}>{fp(net)}</div></div></div>})}</div></Cd>

{/* Payments */}
<Cd s={{padding:"24px 28px",marginBottom:16}}><Lb s={{marginBottom:16}}>🏦 Buyer Payment at This Price</Lb><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[{l:"Conventional (20%)",r:R.c30.r,d:.2},{l:"FHA (3.5%)",r:R.fha.r,d:.035},{l:"VA (0%)",r:R.va.r,d:0}].map(x=>{const ln=ev*(1-x.d),pm=Math.round(pmt(ln,x.r)),tx=Math.round(ev*.011/12),tot=pm+tx+350;return<div key={x.l} style={{padding:16,borderRadius:12,border:`1px solid ${T.bdr}`}}><div style={{fontSize:12,fontWeight:700,color:T.tx,marginBottom:8}}>{x.l}</div><div style={{fontSize:28,fontWeight:900,color:T.tx}}>${fmt(tot)}<span style={{fontSize:12,color:T.mt}}>/mo</span></div><div style={{fontSize:12,color:T.sc,marginTop:6}}>P&I: ${fmt(pm)} · Tax: ${fmt(tx)} · Ins: $350</div><div style={{fontSize:12,color:T.mt,marginTop:4}}>Income needed: ~${fmt(Math.round(tot/.28*12))}/yr</div></div>})}</div></Cd>

<Cd s={{padding:"20px 28px",background:"#f0fdf4",border:"1px solid #bbf7d0"}}><div style={{fontSize:14,fontWeight:800,color:T.tx}}>Prepared by The Encinitas Report</div><div style={{fontSize:12,color:T.sc}}>DRE# 02168977 · theencinitasreport.com · {R.u}</div></Cd>
</>}</>;}

/* ── WEEKLY BRIEF ── */
function Brief(){const[cp,sC]=useState(null);const copy=(t,id)=>{navigator.clipboard?.writeText(t);sC(id);setTimeout(()=>sC(null),2000)};const sc=Math.round((M.s30/M.sp-1)*100),cpmt=Math.round(pmt(M.med*.8,R.c30.r)),hot=[...H].sort((a,b)=>b.chg-a.chg)[0],cool=[...H].sort((a,b)=>a.chg-b.chg)[0];
const email=`Encinitas Market Intel — Week of Feb 10\n\n${fp(M.med)} median | ${M.s30} sold | ${R.c30.r}% rates\n\nTHE BIG PICTURE\n• Median: ${fp(M.med)} (${M.chg}% YoY)\n• Sold 30d: ${M.s30} — up ${sc}%\n• $/sqft: $${M.ppsf} (+${M.pc}%)\n• DOM: ${M.dom} avg (hot: ${M.hd}d)\n\nRATES\n• 30-Yr: ${R.c30.r}% (down from 6.93%!)\n• Median w/ 20% down: $${fmt(cpmt)}/mo\n\nNEIGHBORHOODS\n${H.map(n=>`${n.nm}: ${fp(n.med)} (${n.chg>0?"+":""}${n.chg}%)`).join("\n")}\n\n🔥 ${hot.nm} +${hot.chg}% | ❄️ ${cool.nm} ${cool.chg}%\n\nFull data → theencinitasreport.com\n\nDavid · DRE# 02168977`;
const sms=`📊 Encinitas ${fp(M.med)} median | ${M.s30} sold (↑${sc}%) | ${R.c30.r}% rates\n🔥 ${hot.nm} +${hot.chg}%\n❄️ ${cool.nm} ${cool.chg}%\n→ theencinitasreport.com`;
return<><h1 style={{fontSize:28,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:"0 0 6px"}}>Weekly Market Brief</h1><p style={{fontSize:14,color:T.mt,marginBottom:24}}>Auto-generated — copy and send to your database</p>
<div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:10,marginBottom:24}}>{[[fp(M.med),`${M.chg}%`,"Median"],[M.s30,`↑${sc}%`,"Sold"],[`${R.c30.r}%`,"30yr","Rate"],[M.dom+"d",`Hot:${M.hd}d`,"DOM"],[M.act,`${SL.filter(s=>s.st==="Price Cut").length} cuts`,"Active"]].map(([v,s,l],i)=><Cd key={i} s={{padding:"14px 16px",textAlign:"center"}}><div style={{fontSize:22,fontWeight:900,color:T.tx}}>{v}</div><div style={{fontSize:11,color:T.pos,fontWeight:600}}>{s}</div><div style={{fontSize:10,color:T.mt}}>{l}</div></Cd>)}</div>
{[{id:"email",t:"📧 Email Newsletter",c:email},{id:"sms",t:"📱 SMS Update",c:sms}].map(it=><Cd key={it.id} s={{marginBottom:16,overflow:"hidden"}}><div style={{padding:"16px 24px",borderBottom:`1px solid ${T.bdr}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:16,fontWeight:800,color:T.tx}}>{it.t}</span><button onClick={()=>copy(it.c,it.id)} style={{padding:"6px 14px",borderRadius:8,border:`1px solid ${T.bdr}`,background:T.card,fontSize:12,fontWeight:700,cursor:"pointer",color:cp===it.id?T.pos:T.sc}}>{cp===it.id?"✓ Copied":"📋 Copy"}</button></div><div style={{padding:"16px 24px",maxHeight:250,overflowY:"auto"}}><pre style={{fontSize:13,color:T.tx,lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:0}}>{it.c}</pre></div></Cd>)}
<Cd s={{padding:"20px 24px",background:"#f0fdf4",border:"1px solid #bbf7d0"}}><div style={{fontSize:12,fontWeight:700,color:T.brd,marginBottom:8}}>💡 Distribution: Monday AM email → Wednesday social → Friday video</div></Cd></>;}

/* ── RATES ── */
function Rates(){const[pr,sP]=useState(M.med),[dp,sD]=useState(20);return<><h1 style={{fontSize:28,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:"0 0 6px"}}>Today's Mortgage Rates</h1><p style={{fontSize:14,color:T.mt,marginBottom:24}}>Updated {R.u}</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,marginBottom:24}}>{[R.c30,R.c15,R.fha,R.va,R.jb,R.arm].map(r=><Cd key={r.l} s={{padding:"20px 24px"}}><Lb>{r.l}</Lb><div style={{fontSize:36,fontWeight:900,color:T.tx,letterSpacing:"-2px",marginTop:6}}>{r.r}%</div>{r.n&&<div style={{fontSize:11,color:T.mt,marginTop:6}}>{r.n}</div>}</Cd>)}</div>
<Cd s={{padding:"24px 28px"}}><Lb s={{marginBottom:16}}>Payment Calculator</Lb><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,marginBottom:20}}><div><div style={{fontSize:12,fontWeight:700,color:T.sc,marginBottom:6}}>Home Price</div><input type="range" min={500000} max={5000000} step={25000} value={pr} onChange={e=>sP(+e.target.value)} style={{width:"100%",accentColor:T.br}}/><div style={{fontSize:24,fontWeight:900,color:T.tx}}>{fp(pr)}</div></div><div><div style={{fontSize:12,fontWeight:700,color:T.sc,marginBottom:6}}>Down Payment</div><input type="range" min={0} max={50} value={dp} onChange={e=>sD(+e.target.value)} style={{width:"100%",accentColor:T.br}}/><div style={{fontSize:24,fontWeight:900,color:T.tx}}>{dp}% <span style={{fontSize:14,color:T.mt}}>({fp(pr*dp/100)})</span></div></div></div>
{[{...R.c30,d:dp/100},{...R.c15,d:dp/100,y:15},{...R.fha,d:Math.max(.035,dp/100)},{...R.va,d:0}].map(r=>{const ln=pr*(1-r.d),pm=pmt(ln,r.r,r.y||30);return<div key={r.l} style={{display:"flex",justifyContent:"space-between",padding:"14px 0",borderBottom:`1px solid ${T.bdr}`}}><div><div style={{fontSize:14,fontWeight:700,color:T.tx}}>{r.l}</div><div style={{fontSize:12,color:T.mt}}>{r.r}% · {fp(ln)}</div></div><div style={{fontSize:22,fontWeight:900,color:T.tx}}>${fmt(Math.round(pm))}<span style={{fontSize:12,color:T.mt}}>/mo</span></div></div>})}</Cd></>;}

/* ── HOME VALUE ── */
function HomeVal(){const[st,sS]=useState(1),[ad,sA]=useState("");const inp={width:"100%",padding:"14px 16px",borderRadius:12,border:`1px solid ${T.bdr}`,fontSize:15,fontFamily:"inherit",outline:"none",boxSizing:"border-box",color:T.tx};const btn={marginTop:12,padding:"14px",borderRadius:12,border:"none",fontSize:15,fontWeight:700,background:T.br,color:"white",cursor:"pointer",width:"100%"};return<><h1 style={{fontSize:28,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:"0 0 24px"}}>What's Your Home Worth?</h1><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:32}}><Cd s={{padding:32}}>{st===1&&<><Lb s={{marginBottom:12}}>Enter Address</Lb><input value={ad} onChange={e=>sA(e.target.value)} placeholder="e.g. 412 Neptune Ave" style={inp}/><button onClick={()=>ad&&sS(2)} style={btn}>Get Estimate</button></>}{st===2&&<><Lb s={{marginBottom:12}}>Where to send?</Lb>{["Full Name","Email","Phone"].map(p=><input key={p} placeholder={p} style={{...inp,marginBottom:10}}/>)}<button onClick={()=>sS(3)} style={btn}>See Estimate</button></>}{st===3&&<div style={{textAlign:"center"}}><div style={{fontSize:12,fontWeight:700,color:T.br}}>ESTIMATED VALUE</div><div style={{fontSize:48,fontWeight:900,color:T.tx,letterSpacing:"-2px"}}>{fp(M.med)}</div><button onClick={()=>sS(1)} style={{...btn,background:"transparent",border:`2px solid ${T.br}`,color:T.br,marginTop:20}}>Request Free CMA</button></div>}</Cd><Cd s={{padding:"24px 28px"}}><Lb>Neighborhood Medians</Lb><div style={{marginTop:16}}>{H.map(n=><div key={n.id} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:"1px solid #f1f5f9"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:3,background:n.cl}}/><span style={{fontSize:13,fontWeight:600,color:T.tx}}>{n.nm}</span></div><div style={{display:"flex",gap:12}}><span style={{fontSize:13,fontWeight:800,color:T.tx}}>{fp(n.med)}</span><span style={{fontSize:12,fontWeight:600,color:n.chg>0?T.pos:T.neg}}>{n.chg>0?"+":""}{n.chg}%</span></div></div>)}</div></Cd></div></>;}

/* ── CONTENT ENGINE (gated) ── */
function Content({onLock}){const[hd,sH]=useState("leucadia"),[cp,sC]=useState(null);const h=H.find(n=>n.id===hd)||H[0],hp=Math.round(pmt(h.med*.8,R.c30.r)),hv=Math.round(pmt(h.med,R.va.r)),sc=Math.round((M.s30/M.sp-1)*100);const copy=(t,id)=>{navigator.clipboard?.writeText(t);sC(id);setTimeout(()=>sC(null),2000)};
const social=`🏘️ ${h.nm} Snapshot\n\n🏷 ${fp(h.med)} (${h.chg>0?"+":""}${h.chg}%)\n⏱ ${h.dom}d DOM | 🏆 ${h.sc}/100\n💰 $${h.ppsf}/sqft\n\n💵 Conv: $${fmt(hp)}/mo | VA: $${fmt(hv)}/mo\n\n→ theencinitasreport.com\n#Encinitas #${h.nm.replace(/[^a-zA-Z]/g,"")}`;
return<><div style={{display:"flex",justifyContent:"space-between",marginBottom:20}}><div><h1 style={{fontSize:28,fontWeight:900,color:T.tx,letterSpacing:"-1px",margin:"0 0 4px"}}>Content Engine</h1><p style={{fontSize:14,color:T.mt,margin:0}}>Scripts & social posts from live data</p></div><button onClick={onLock} style={{padding:"8px 16px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"white",color:T.sc,fontSize:12,fontWeight:600,cursor:"pointer"}}>🔒 Lock</button></div>
<div style={{marginBottom:20}}><Lb s={{marginBottom:6}}>Neighborhood</Lb><select value={hd} onChange={e=>sH(e.target.value)} style={{padding:"10px 16px",borderRadius:10,fontSize:14,background:"white",border:`1px solid ${T.bdr}`,color:T.tx,fontWeight:600}}>{H.map(n=><option key={n.id} value={n.id}>{n.nm}</option>)}</select></div>
<Cd s={{marginBottom:16,overflow:"hidden"}}><div style={{padding:"16px 24px",borderBottom:`1px solid ${T.bdr}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:16,fontWeight:800,color:T.tx}}>📊 Weekly Market Script</span><button onClick={()=>copy(`Median ${fp(M.med)}, ${M.s30} sold, rates ${R.c30.r}%`,"s")} style={{padding:"6px 14px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"white",fontSize:11,fontWeight:700,cursor:"pointer",color:cp==="s"?T.pos:T.sc}}>{cp==="s"?"✓":"📋"} Copy</button></div>{[{h:"🎬 HOOK",b:`Median ${fp(M.med)}, down ${Math.abs(M.chg)}%. But ${M.s30} sold—UP ${sc}%. $/sqft UP ${M.pc}%.`},{h:"💰 RATES",b:`Conv ${R.c30.r}%. On median: $${fmt(Math.round(pmt(M.med*.8,R.c30.r)))}/mo. VA: $${fmt(Math.round(pmt(M.med,R.va.r)))}/mo.`},{h:"🏘️ HOODS",b:H.map(n=>`${n.nm}: ${fp(n.med)} (${n.chg>0?"+":""}${n.chg}%)`).join(" | ")},{h:"📣 CTA",b:`theencinitasreport.com · DRE# 02168977`}].map((s,i)=><div key={i} style={{padding:"12px 24px",borderBottom:`1px solid ${T.bdr}`}}><div style={{fontSize:12,fontWeight:800,color:T.lb,marginBottom:4}}>{s.h}</div><div style={{fontSize:13,color:T.tx,lineHeight:1.6}}>{s.b}</div></div>)}</Cd>
<Cd s={{overflow:"hidden"}}><div style={{padding:"16px 24px",borderBottom:`1px solid ${T.bdr}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:16,fontWeight:800,color:T.tx}}>📱 Social Post</span><button onClick={()=>copy(social,"p")} style={{padding:"6px 14px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"white",fontSize:11,fontWeight:700,cursor:"pointer",color:cp==="p"?T.pos:T.sc}}>{cp==="p"?"✓":"📋"} Copy</button></div><div style={{padding:"16px 24px"}}><pre style={{fontSize:13,color:T.tx,lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:0}}>{social}</pre></div></Cd></>;}

/* ── MAIN APP ── */
export default function App(){const[tab,sT]=useState("dash"),[unlk,sU]=useState(false),[pw,sP]=useState(""),[err,sE]=useState(false);const go=t=>{sT(t);window.scrollTo({top:0,behavior:"smooth"})};const unlck=()=>{if(pw==="apex2026"){sU(true);sE(false);}else{sE(true);sP("");}};
const tabs=[{id:"dash",l:"Dashboard"},{id:"rates",l:"Rates"},{id:"permits",l:"Permits"},{id:"value",l:"Home Value"},{id:"intel",l:"Intel Report"},{id:"brief",l:"Weekly Brief"},{id:"content",l:"Content"}];
return<div style={{minHeight:"100vh",background:T.bg,color:T.tx,fontFamily:"-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif"}}>
<nav style={{background:T.card,borderBottom:`1px solid ${T.bdr}`,padding:"0 20px",height:64,display:"flex",alignItems:"center",justifyContent:"space-between",position:"sticky",top:0,zIndex:100}}>
<div onClick={()=>go("dash")} style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}}><Logo sz={34}/><div><div style={{fontSize:15,fontWeight:800,color:T.tx,letterSpacing:"-0.3px",lineHeight:1.1}}>The Encinitas Report</div><div style={{fontSize:9,color:T.mt,fontWeight:600}}>DRE# 02168977</div></div></div>
<div style={{display:"flex",gap:1}}>{tabs.map(t=><button key={t.id} onClick={()=>go(t.id)} style={{padding:"7px 12px",borderRadius:8,fontSize:11.5,fontWeight:tab===t.id?700:500,cursor:"pointer",background:"transparent",border:tab===t.id?`1.5px solid ${T.tx}`:"1.5px solid transparent",color:tab===t.id?T.tx:T.sc}}>{t.l}</button>)}</div>
</nav>
<div style={{maxWidth:1200,margin:"0 auto",padding:"32px 32px 80px"}}>
{tab==="dash"&&<Dash/>}{tab==="rates"&&<Rates/>}{tab==="permits"&&<Permits/>}{tab==="value"&&<HomeVal/>}{tab==="intel"&&<Intel/>}{tab==="brief"&&<Brief/>}
{tab==="content"&&(unlk?<Content onLock={()=>{sU(false);sP("");}}/>:<div style={{maxWidth:400,margin:"80px auto",textAlign:"center"}}><div style={{width:64,height:64,borderRadius:16,background:"#f1f5f9",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 20px",fontSize:28}}>🔒</div><h2 style={{fontSize:22,fontWeight:800,color:T.tx,margin:"0 0 8px"}}>Content Engine</h2><p style={{fontSize:14,color:T.mt,marginBottom:24}}>Enter passcode</p><input type="password" value={pw} onChange={e=>{sP(e.target.value);sE(false);}} onKeyDown={e=>e.key==="Enter"&&unlck()} placeholder="Passcode" style={{width:"100%",padding:"14px 16px",borderRadius:12,border:`1.5px solid ${err?T.neg:T.bdr}`,fontSize:15,textAlign:"center",outline:"none",boxSizing:"border-box",color:T.tx}}/>{err&&<div style={{fontSize:13,color:T.neg,marginTop:8}}>Incorrect</div>}<button onClick={unlck} style={{marginTop:12,padding:"14px",borderRadius:12,border:"none",fontSize:15,fontWeight:700,background:T.br,color:"white",cursor:"pointer",width:"100%"}}>Unlock</button></div>)}
</div>
<div style={{borderTop:`1px solid ${T.bdr}`,padding:"24px 32px",display:"flex",justifyContent:"space-between",maxWidth:1200,margin:"0 auto",flexWrap:"wrap",gap:8}}><div style={{display:"flex",alignItems:"center",gap:8}}><LogoSm sz={20}/><span style={{fontSize:12,color:T.mt}}>© 2026 The Encinitas Report · DRE# 02168977</span></div><span style={{fontSize:11,color:"#cbd5e1"}}>Data: Redfin, Zillow, MLS, City of Encinitas, SD County Assessor</span></div>
</div>;}
